load("//devtools/python/blaze:pytype.bzl", "pytype_strict_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

pytype_strict_library(
    name = "common_flags",
    srcs = ["common_flags.py"],
    deps = ["//third_party/py/absl/flags"],
)
